image_selector/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from image_selector import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('selector.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__reload__/", include("django_browser_reload.urls")),

selector/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("overview/", views.overview, name="overview"),
    path("base/", views.base, name="base"),
    path("login/", auth_views.LoginView.as_view(template_name="selector/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("admin_users/", views.AdminUserListView.as_view(), name="admin_users"),

    path("devices/", views.DeviceListView.as_view(), name="devices"),
    path("all_devices/", views.AllDeviceListView.as_view(), name="all_devices"),
    path("devices/<int:pk>/", views.DeviceDetailView.as_view(), name="device_detail"),
    path("devices/<int:pk>/delete/", views.DeviceDeleteView.as_view(), name="device_delete"),
    path("devices/<int:pk>/update/", views.DeviceUpdateView.as_view(), name="device_update"),
    path("devices/new/", views.DeviceCreateView.as_view(), name="device_new"),

    path("albums/", views.AlbumListView.as_view(), name="albums"),
    path("all_albums/", views.AllAlbumListView.as_view(), name="all_albums"),
    path("albums/new/", views.AlbumCreateView.as_view(), name="album_new"),
    path("albums/<int:album_id>/", views.PictureListView.as_view(), name="pictures"),
    path("albums/<int:pk>/update/", views.AlbumUpdateView.as_view(), name="album_update"),
    path("albums/<int:pk>/delete/", views.AlbumDeleteView.as_view(), name="album_delete"),

    path("albums/<int:album_id>/images/create", views.Upload.as_view(), name="upload_image"),



    # API
    path("last_image/", views.LastImage.as_view(), name="last_image"),
    path("last_image_raw/", views.LastImageRaw.as_view(), name="last_image_raw"),
    path("next_wakeup/", views.NextWakeup.as_view(), name="next_wakeup"),
    path("current_image_id/", views.CurrentImageId.as_view(), name="current_image_id"),
]

selector/models.py
import random
from datetime import timedelta, datetime
from typing import Optional

from croniter import croniter
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


# Create your models here.


class User(AbstractUser):
    class Meta:
        permissions = [
            ("view_user_admin", "Can view all users"),
        ]

    # class Meta:
    #     permissions = [
    #         ("view_users", "Can view users"),
    #
    #     ]


class BateryLevel(models.Model):
    level = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)
    device = models.ForeignKey('Device', on_delete=models.CASCADE, related_name='battery_levels')

    def __str__(self):
        return f'{self.level}V'


class Device(models.Model):
    token = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    last_seen = models.DateTimeField(null=True, blank=True)
    last_seen_ip = models.CharField(max_length=100, null=True, blank=True)
    last_battery_level = models.FloatField(null=True, blank=True)
    user = models.ForeignKey('User', on_delete=models.DO_NOTHING, related_name='devices')
    picture_group = models.ForeignKey('PictureGroup', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        permissions = [
            ("view_devices", "Can view devices"),
            ("view_device_admin", "Can view all devices"),
        ]

    def set_last_battery_level(self, level):
        self.last_battery_level = level
        self.save()
        BateryLevel.objects.create(level=level, device=self)

    @property
    def status(self):
        if self.last_seen is None:
            return 'offline'

        if timezone.now() - self.last_seen > timedelta(days=2):
            return 'offline'
        elif timezone.now() - self.last_seen > timedelta(days=1) or (
                self.last_battery_level < 3.4) if self.last_battery_level else False:
            return 'warning'
        else:
            return 'online'

    @property
    def status_message(self):
        status = ""

        if self.last_seen is None:
            return 'Device has never been seen.'
        elif timezone.now() - self.last_seen > timedelta(days=2):
            status = 'Device was last seen more than 2 days ago.'
        elif timezone.now() - self.last_seen > timedelta(days=1):
            status = 'Device was last seen more than 1 day ago.'

        if self.last_battery_level and self.last_battery_level < 3.4:
            status += '\n Battery level is low.'

        return status

    def __str__(self):
        return self.name


class Picture(models.Model):
    name = models.CharField(max_length=100)
    upload_data = models.DateTimeField(auto_now_add=True)
    last_view_date = models.DateTimeField(null=True, blank=True)
    image = models.ImageField(upload_to='images/')
    raw_image = models.ImageField(upload_to='images_raw/')

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        self.raw_image.delete()
        super().delete(using=using, keep_parents=keep_parents)

    def __str__(self):
        return self.name


class PictureGroup(models.Model):
    name = models.CharField(max_length=100)
    schedule = models.CharField(max_length=100)
    pictures = models.ManyToManyField('Picture', blank=True, related_name='picture_group')
    current_picture = models.ForeignKey('Picture', on_delete=models.SET_NULL, null=True, blank=True,
                                        related_name='current_picture_for_group')
    current_picture_valid_until = models.DateTimeField(null=True, blank=True)
    users = models.ManyToManyField('User', blank=True, related_name='picture_groups')
    admins = models.ManyToManyField('User', related_name='admin_picture_groups')

    class Meta:
        permissions = [
            ("view_picturegroup_admin", "Can view all picture groups"),
        ]

    def get_new_picture(self) -> Optional[Picture]:

        if self.pictures.count() == 1:
            return self.pictures.first()

        if self.pictures.count() == 0:
            return None

        never_played = list(
            Picture.objects.filter(last_view_date__isnull=True, picture_group=self).values_list('id',
                                                                                                flat=True))
        played = list(Picture.objects
                      .filter(last_view_date__isnull=False, picture_group=self)
                      .exclude(id=self.current_picture.id)
                      .order_by('last_view_date').values_list('id', flat=True))

        weights = [len(played) + 1] * len(never_played) + list(range(len(played), 0, -1))
        print(list(zip(never_played + played, weights)))
        new_picture_id = random.choices(never_played + played, weights=weights, k=1)[0]
        return Picture.objects.get(id=new_picture_id)

    def get_last_picture(self) -> Optional[Picture]:
        print(self.current_picture_valid_until, timezone.now())
        # print(self.current_picture_valid_until > timezone.now())
        if not self.current_picture_valid_until or self.current_picture_valid_until < timezone.now() or not self.current_picture:
            print("Getting new picture")
            new_picture = self.get_new_picture()
            if not new_picture:
                return None
            new_picture.last_view_date = timezone.now()
            new_picture.save()

            self.current_picture = new_picture
            self.current_picture_valid_until = croniter(self.schedule,
                                                        timezone.localtime(timezone.now())).get_next(datetime)

            self.save()
        return self.current_picture

    def __str__(self):
        return self.name

selector/forms.py
import hashlib
import random

from croniter import croniter
from django import forms
from django.db.models import Q

from selector.models import PictureGroup, Device


class AlbumForm(forms.ModelForm):
    class Meta:
        model = PictureGroup
        fields = ["name", "schedule", "users"]
        widgets = {
            'users': forms.SelectMultiple(attrs={'class': 'form-control'}),
            "schedule": forms.TextInput(
                attrs={'placeholder': '0 0 * * *', "class": "form-control", "value": "0 0 * * *"}),
            # 0 0 * * * = every day at midnight
            "name": forms.TextInput(attrs={'placeholder': 'Album name', "class": "form-control"}),
        }

    def clean_schedule(self):
        schedule = self.cleaned_data['schedule']

        if not croniter.is_valid(schedule):
            raise forms.ValidationError("Schedule must be a valid cron expression.")
        return schedule


class AlbumFormUpdate(forms.ModelForm):
    class Meta:
        model = PictureGroup
        fields = ["name", "schedule", "users", "admins"]
        widgets = {
            'users': forms.SelectMultiple(attrs={'class': 'form-control'}),
            "schedule": forms.TextInput(
                attrs={'placeholder': '0 0 * * *', "class": "form-control", "value": "0 0 * * *"}),
            # 0 0 * * * = every day at midnight
            "name": forms.TextInput(attrs={'placeholder': 'Album name', "class": "form-control"}),
            'admins': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    def clean_schedule(self):
        schedule = self.cleaned_data['schedule']

        if not croniter.is_valid(schedule):
            raise forms.ValidationError("Schedule must be a valid cron expression.")
        return schedule


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = ["name", "picture_group"]
        exclude = ("token", "user",)
        widgets = {
            "name": forms.TextInput(attrs={'placeholder': 'Device name', "class": "form-control"}),
            'picture_group': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        # user = kwargs.pop('user', None)
        super(DeviceForm, self).__init__(*args, **kwargs)
        self.fields['picture_group'].queryset = PictureGroup.objects.filter(Q(users=user) | Q(admins=user)).distinct()

templates/selector/base.html
{% load static %}
{% load active_link %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description"
          content="Sleek Dashboard - Free Bootstrap 4 Admin Dashboard Template and UI Kit. It is very powerful bootstrap admin dashboard, which allows you to build products like admin panels, content management systems and CRMs etc.">

    <!-- theme meta -->
    <meta name="theme-name" content="sleek"/>

    <title>Direct Picture Sync</title>

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500"
          rel="stylesheet"/>

    <link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet"/>

    <!-- PLUGINS CSS STYLE -->
    {#    <link href="{% static 'assets/plugins/simplebar/simplebar.css' %}" rel="stylesheet"/>#}
    <link href="{% static 'assets/plugins/nprogress/nprogress.css' %}" rel="stylesheet"/>

    <!-- No Extra plugin used -->
    <link href='{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.css' %}' rel='stylesheet'>
    <link href='{% static 'assets/plugins/daterangepicker/daterangepicker.css' %}' rel='stylesheet'>


    <link href='{% static 'assets/plugins/toastr/toastr.min.css' %}' rel='stylesheet'>

    <!-- SLEEK CSS -->
    <link id="sleek-css" rel="stylesheet" href="{% static 'assets/css/sleek.css' %}"/>

    <!-- FAVICON -->
    <link href="{% static 'assets/img/favicon.png" rel="shortcut icon' %}"/>

    <!--
      HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{% static 'assets/plugins/nprogress/nprogress.js' %}"></script>
    {% block head %}
    {% endblock %}
</head>

<body class="header-fixed sidebar-fixed sidebar-dark header-light" id="body">
<script>
    NProgress.configure({showSpinner: false});
    NProgress.start();
</script>

<div id="toaster"></div>

<!-- ====================================
——— WRAPPER
===================================== -->
<div class="wrapper">

    <!-- ====================================
      ——— LEFT SIDEBAR WITH OUT FOOTER
    ===================================== -->
    <aside class="left-sidebar bg-sidebar">
        <div id="sidebar" class="sidebar sidebar-with-footer">
            <!-- Aplication Brand -->
            <div class="app-brand">
                <a href="/" title="Sleek Dashboard">
                    <svg
                            class="brand-icon"
                            xmlns="http://www.w3.org/2000/svg"
                            preserveAspectRatio="xMidYMid"
                            width="30"
                            height="33"
                            viewBox="0 0 30 33">
                        <g fill="none" fill-rule="evenodd">
                            <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z"/>
                            <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z"/>
                        </g>
                    </svg>

                    <span class="brand-name text-truncate">DPS Dashboard</span>
                </a>
            </div>

            <!-- begin sidebar scrollbar -->
            <div class="" data-simplebar style="height: 100%;">
                <!-- sidebar menu -->
                <ul class="nav sidebar-inner" id="sidebar-menu">
                    {% if perms.selector.view_picturegroup %}
                        <li class="{% active_link "albums" "active" %}">
                            <a class="sidenav-item-link" href="/albums"
                               aria-expanded="false" aria-controls="dashboard">
                                <iconify-icon icon="jam:pictures-f" style="color: #a6aab4;margin-right: 15px" width="30px"></iconify-icon>

                                <span class="nav-text">Albums</span> <b class="caret"></b>
                            </a>
                        </li>
                    {% endif %}

                    {% if perms.selector.view_device %}
                        <li class="{% active_link "devices" "active" %}">
                            <a class="sidenav-item-link" href="/devices"
                               aria-expanded="false" aria-controls="app">
                                <iconify-icon icon="bxs:microchip" style="color: #a6aab4;margin-right: 15px" width="30px"></iconify-icon>
                                <span class="nav-text">Devices</span> <b class="caret"></b>
                            </a>
                        </li>
                    {% endif %}

                    {% if perms.selector.view_picturegroup_admin %}
                        <li class="{% active_link "all_albums" "active" %}">
                            <a class="sidenav-item-link" href="/all_albums"
                               aria-expanded="false" aria-controls="app">
                                <iconify-icon icon="jam:pictures-f" style="color: #a6aab4;margin-right: 15px" width="30px"></iconify-icon>
                                <span class="nav-text">All albums</span> <b class="caret"></b>
                            </a>
                        </li>
                    {% endif %}

                {% if perms.selector.view_device_admin %}
                        <li class="{% active_link "all_devices" "active" %}">
                            <a class="sidenav-item-link" href="/all_devices"
                               aria-expanded="false" aria-controls="app">
                                <iconify-icon icon="bxs:microchip" style="color: #a6aab4;margin-right: 15px" width="30px"></iconify-icon>
                                <span class="nav-text">All Devices</span> <b class="caret"></b>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </aside>


    <!-- ====================================
  ——— PAGE WRAPPER
  ===================================== -->
    <div class="page-wrapper">

        <!-- Header -->
        <header class="main-header " id="header">
            <nav class="navbar navbar-static-top navbar-expand-lg">
                <!-- Sidebar toggle button -->
                <button id="sidebar-toggler" class="sidebar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                </button>
                <!-- search form -->
                <div class="search-form d-none d-lg-inline-block">
                </div>

                <div class="navbar-right ">
                    <ul class="nav navbar-nav">
                        <!-- User Account -->
                        <li class="dropdown user-menu">
                            <button href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                {#                                <img src="{% static 'assets/img/user/user.png' %}" class="user-image" alt="User Image"/>#}
                                <span class="d-none d-lg-inline-block">{{ user.username }}</span>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li class="dropdown">
                                    <a href="{% url 'logout' %}"> <i class="mdi mdi-logout"></i> Log Out </a>
                                </li>
                                {% if perms.selector.view_user_admin%}
                                <li class="dropdown">
                                    <a href="{% url 'admin_users' %}"><iconify-icon icon="teenyicons:users-solid" style="color: #a6aab4;margin-right: 15px"></iconify-icon> Users</a>
                                </li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>


        <!-- ====================================
        ——— CONTENT WRAPPER
        ===================================== -->
        <div class="content-wrapper">
            <div class="content">

                {% block content %}{% endblock %}

            </div> <!-- End Content -->
        </div> <!-- End Content Wrapper -->


        <!-- Footer -->
        <footer class="footer mt-auto">
            <div class="copyright bg-white">
                <p>
                    Copyright &copy; <span id="copy-year"></span> Rozekrans Computer Services
                </p>
            </div>
            <script>
                var d = new Date();
                var year = d.getFullYear();
                document.getElementById("copy-year").innerHTML = year;
            </script>
        </footer>

    </div> <!-- End Page Wrapper -->
</div> <!-- End Wrapper -->


<!-- <script type="module">
  import 'https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate';

  const el = document.createElement('pwa-update');
  document.body.appendChild(el);
</script> -->

<!-- Javascript -->
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{#<script src="{% static 'assets/plugins/simplebar/simplebar.min.js' %}"></script>#}

<script src="https://cdn.jsdelivr.net/npm/chart.js@^3"></script>
<script src="https://cdn.jsdelivr.net/npm/luxon@^2"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@^1"></script>
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@2.0.1/dist/chartjs-plugin-zoom.min.js"></script>


<script src='{% static 'assets/js/chart.js' %}'></script>


<script src='{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js' %}'></script>
<script src='{% static 'assets/plugins/jvectormap/jquery-jvectormap-world-mill.js' %}'></script>
{#<script src='{% static 'assets/js/vector-map.js' %}'></script>#}

<script src='{% static 'assets/plugins/daterangepicker/moment.min.js' %}'></script>
<script src='{% static 'assets/plugins/daterangepicker/daterangepicker.js' %}'></script>
<script src='{% static 'assets/js/date-range.js' %}'></script>


<script src='{% static 'assets/plugins/toastr/toastr.min.js' %}'></script>
{#<script src="//code.iconify.design/1/1.0.6/iconify.min.js"></script>#}
<script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>


<script src="{% static 'assets/js/sleek.js' %}"></script>
{#<link href="{% static 'assets/options/optionswitch.css' %}" rel="stylesheet">#}
{#<script src="{% static 'assets/options/optionswitcher.js' %}"></script>#}

{% block scripts %}{% endblock %}

</body>
</html>

templates/selector/index.html
{% extends "selector/base.html" %}

templates/selector/picturegroup_form.html
{% extends "selector/base.html" %}
{% load switch %}

{% block content %}

    <div class="breadcrumb-wrapper d-flex align-items-center justify-content-between">
        <div>
            {% if object %}
                <h1>Edit Album</h1>
            {% else %}
                <h1>Create new Album</h1>
            {% endif %}


            <nav aria-label="breadcrumb">
                <ol class="breadcrumb p-0">
                    <li class="breadcrumb-item">
                        <a href="/">
                            <span class="mdi mdi-home"></span>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/albums/"> albums</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/albums/{{ object.id }}">{{ object.name }}</a>
                    </li>
                </ol>
            </nav>

        </div>
    </div>

    <div class="row">
        <div class="col-12">

            <!-- Recent Order Table -->
            <div class="card card-table-border-none recent-orders" id="recent-orders">
                <div class="card-header justify-content-between">
                    {% if object %}
                        <h2>Edit Album {{ object.name }}</h2>
                    {% else %}
                        <h2>Create new Album</h2>
                    {% endif %}
                </div>

                <div class="card-body pt-0 pb-5">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            {{ form.errors }}
                        </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.name.id_for_label }}"
                                   class="form-label">{{ form.name.label }}</label>
                            {{ form.name }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.schedule.id_for_label }}"
                                   class="form-label">{{ form.schedule.label }}</label>
                            {{ form.schedule }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.users.id_for_label }}"
                                   class="form-label">{{ form.users.label }}</label>
                            {{ form.users }}
                        </div>

                        {% if form.admins %}
                            <div class="mb-3">
                                <label for="{{ form.admins.id_for_label }}"
                                       class="form-label">{{ form.admins.label }}</label>
                                {{ form.admins }}
                            </div>
                        {% endif %}
                        {% if object %}
                            <input type="submit" class="btn btn-primary" value="Update ">

                        {% else %}
                            <input type="submit" class="btn btn-primary" value="Create">

                        {% endif %}
                        <a href="/albums" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
            </div>

        </div>
    </div>

    {#    <div class="row">#}
    {#        <div class="col-12">#}
    {##}
    {#            <!-- Recent Order Table -->#}
    {#            <div class="card card-table-border-none recent-orders" id="recent-orders">#}
    {#                <div class="card-header justify-content-between">#}
    {#                    <h2>Albums</h2>#}
    {#                </div>#}
    {#                <div class="row row-cols-1 row-cols-md-4" style="padding: 10px">#}
    {#                    {% for album in albums %}#}
    {#                        <div class="col mb-4">#}
    {#                            <div class="card">#}
    {#                                <a href="/albums/{{ album.id }}">#}
    {##}
    {#                                    <img class="card-img-top"#}
    {#                                         src="{{ album.get_last_picture.image.url|default:"https://via.placeholder.com/150" }}"#}
    {#                                         alt="Card image cap">#}
    {#                                </a>#}
    {##}
    {##}
    {#                                <div class="card-body">#}
    {#                                    <div class="dropdown show" style="float: right">#}
    {#                                        <a class="" href="#" role="button"#}
    {#                                           id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"#}
    {#                                           aria-expanded="false">#}
    {#                                            <i class="mdi mdi-dots-vertical" style="float: right;font-size: 24px"></i>#}
    {##}
    {#                                        </a>#}
    {##}
    {#                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink"#}
    {#                                             style="float: right">#}
    {#                                            <a class="dropdown-item" href="/albums/{{ album.id }}">View</a>#}
    {#                                            {% if perms.selector.change_picturegroup %}#}
    {#                                                <a class="dropdown-item" href="#">Edit</a>#}
    {#                                            {% endif %}#}
    {#                                            {% if perms.selector.delete_picturegroup %}#}
    {#                                                <a class="dropdown-item" href="#">Delete</a>#}
    {#                                            {% endif %}#}
    {#                                        </div>#}
    {#                                    </div>#}
    {##}
    {#                                    <a href="/albums/{{ album.id }}">#}
    {#                                        <h5 class="card-title text-primary">{{ album.name }}</h5>#}
    {#                                    </a>#}
    {#                                    <div class="text-muted">Next#}
    {#                                        update: {{ album.current_picture_valid_until|date:"F j, Y, G:i"|default:"unknown" }}#}
    {##}
    {#                                    </div>#}
    {##}
    {##}
    {#                                </div>#}
    {##}
    {#                            </div>#}
    {#                        </div>#}
    {##}
    {##}
    {#                    {% empty %}#}
    {#                        <div class="col mb-4">#}
    {#                            No albums#}
    {#                        </div>#}
    {##}
    {#                    {% endfor %}#}
    {#                </div> <div class="col mb-4">#}
    {##}
    {#            </div>#}
    {##}
    {#        </div>#}
    {#    </div>#}


    <!-- Modal -->

    {#    <div class="modal" tabindex="-1" role="dialog" id="modal-add-album">#}
    {#        <div class="modal-dialog" role="document">#}
    {#            <div class="modal-content">#}
    {#                <div class="modal-header">#}
    {#                    <h5 class="modal-title" id="delete_model_title">Add new Album</h5>#}
    {#                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">#}
    {#                        <span aria-hidden="true">&times;</span>#}
    {#                    </button>#}
    {#                </div>#}
    {#                <div class="modal-body">#}
    {#                    <div class="mb-3">#}
    {#                        <label for="{{ AlbumForm.name.id_for_label }}"#}
    {#                               class="form-label">{{ AlbumForm.name.label }}</label>#}
    {#                        {{ AlbumForm.name }}#}
    {#                    </div>#}
    {#                    <div class="mb-3">#}
    {#                        <label for="{{ AlbumForm.schedule.id_for_label }}"#}
    {#                               class="form-label">{{ AlbumForm.schedule.label }}</label>#}
    {#                        {{ AlbumForm.schedule }}#}
    {#                    </div>#}
    {#                    <div class="mb-3">#}
    {#                        <label for="{{ AlbumForm.users.id_for_label }}"#}
    {#                               class="form-label">{{ AlbumForm.users.label }}</label>#}
    {#                        {{ AlbumForm.users }}#}
    {#                    </div>#}
    {#                </div>#}
    {#                <div class="modal-footer">#}
    {#                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
    {#                    <button type="button" class="btn btn-primary">save</button>#}
    {##}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}




{% endblock %}

{% block scripts %}

{% endblock %}